CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create table if not exists chat
(
    id         bigint generated by default as identity not null,
    created_at timestamptz  default now()              not null,
    title      varchar(100) default 'New chat'         not null,
    constraint chat_pkey primary key (id)
);


create table if not exists chat_message
(
    id         bigint generated by default as identity not null,
    content    text                                    not null,
    created_at timestamptz default now()               not null,
    role       varchar(20)                             not null,
    chat_id    bigint                                  not null,
    constraint chat_message_pkey primary key (id)
);

alter table chat_message
    add constraint fk_chat_message_chat foreign key (chat_id) references chat (id) on delete cascade;
create index idx_chat_message_chat_created_at on chat_message (chat_id, created_at);


create table if not exists processed_document
(
    id            bigint generated by default as identity not null,
    filename      varchar(255)                            not null,
    content_hash  varchar(64)                             not null,
    document_type varchar(10)                             not null,
    chunk_count   integer                                 not null,
    created_at    timestamptz default now()               not null,
    constraint processed_document_pkey primary key (id),
    constraint unique_document unique (filename, content_hash)
);

create index idx_processed_document_filename on processed_document (filename);

create table if not exists vector_store
(
    id         uuid        DEFAULT uuid_generate_v4() not null,
    content    text                                   not null,
    metadata   jsonb                                  not null,
    embedding  vector(1024)                           not null,
    created_at timestamptz default now()              not null,
    constraint vector_store_pkey primary key (id)
);

create index vector_store_hnsw_index on vector_store using hnsw (embedding vector_cosine_ops);
